package pt.estg.sd.alertops.utils;

public enum RequestType {
    LOGIN, REGISTER,GET_USERS,UPDATE_ROLE,DELETE_USER, OPEN_EMERGENCY_SEND_VIEW,NEW_REQUEST,
    GET_REQUESTS,ACCEPT_REQUEST,DECLINE_REQUEST,GET_CHANNELS,DELETE_CHANNEL,ENTER_CHAT,
    CREATE_GROUP,CREATE_CHAT,SEND_MESSAGE
}
