package pt.estg.sd.alertops.utils;

public enum ResponseType {
    LOGIN_SUCCESS, LOGIN_FAILED, REGISTER_SUCCESS, REGISTER_FAILED,GET_USERS_SUCCESS,GET_USERS_FAILED,
    UPDATE_ROLE_SUCCESS,UPDATE_ROLE_FAILED,DELETE_USER_SUCCESS,DELETE_USER_FAILED, OPEN_SUCCESS, OPEN_FAILED,
    NEW_REQUEST_SUCCESS, NEW_REQUEST_FAILURE, INVALID_REQUEST,GET_REQUESTS_SUCCESS,GET_REQUESTS_FAILED,
    ACCEPT_REQUEST_SUCCESS, ACCEPT_REQUEST_FAILED, DECLINE_REQUEST_SUCCESS, DECLINE_REQUEST_FAILED, REPORT,GET_CHANNELS_SUCCESS,GET_CHANNELS_FAILED,
    DELETE_CHANNEL_SUCCESS,DELETE_CHANNEL_FAILED,ENTER_CHAT_SUCCESS,ENTER_CHAT_FAILED,CREATE_GROUP_SUCCESS,CREATE_GROUP_FAILED,
    CHAT_EXISTS,CREATE_CHAT_SUCCESS,CREATE_CHAT_FAILED,SEND_MESSAGE_SUCCESS,SEND_MESSAGE_FAILED,MESSAGE_RECEIVED_SUCCESS, ENTER_GROUP_CHAT_SUCCESS
}
